const express = require('express')
const util = require('./util')
const authorize = require('./middleware/authorize')
const system = require('./controllers/SystemController.js')
const authen = require('./controllers/LoginController.js')
const userAccount = require('./controllers/UserAccountController.js')
const product = require('./controllers/ProductController.js')
const accessory = require('./controllers/AccessoryController.js')
const orderHeader = require('./controllers/OrderHeaderController.js')
const orderDetail = require('./controllers/OrderDetailController.js')

module.exports = express.Router()
  .post('/login', authen.login)
  .post('/register', authen.register)
  .get('/logout', authen.logout)
  .post('/resetPassword', authen.resetPassword)
  .get('/changePassword/:token', authen.getChangePassword)
  .post('/changePassword/:token', authen.changePassword)
  .get('/user', authen.user)
  .get('/profile', system.profile)
  .post('/updateProfile', system.updateProfile)
  .get('/stack', system.stack)
  .use('/userAccounts', authorize('ADMIN'), express.Router()
    .get('/', userAccount.index)
    .post('/', userAccount.create)
    .get('/create', userAccount.getCreate)
    .get('/:id', userAccount.get)
    .get('/:id/edit', userAccount.edit)
    .put('/:id', userAccount.update)
    .get('/:id/delete', userAccount.getDelete)
    .delete('/:id', userAccount.delete)
  )
  .use('/products', authorize('ADMIN,USER'), express.Router()
    .get('/', product.index)
    .get('/all', product.getAll)
    .post('/', util.getFile('products', 'image'), product.create)
    .get('/create', product.getCreate)
    .post('/selected', util.getFile('products', 'image'), product.getSelected)
    .get('/:id', product.get)
    .get('/:id/edit', product.edit)
    .put('/:id', util.getFile('products', 'image'), product.update)
    .get('/:id/delete', product.getDelete)
    .delete('/:id', product.delete)
  )
  .use('/accessory', authorize('ADMIN,USER'), express.Router()
    .get('/', accessory.index)
    .post('/', accessory.create)
    .get('/create', accessory.getCreate)
    .get('/:id', accessory.get)
    .get('/similar/:name/:value', accessory.getSimilar)
    .get('/:id/edit', accessory.edit)
    .put('/:id', accessory.update)
    .get('/:id/delete', accessory.getDelete)
    .delete('/:id', accessory.delete)
  )
  .use('/orderHeaders', authorize('ADMIN,USER'), express.Router()
    .get('/', orderHeader.index)
    .get('/all', orderHeader.getAll)
    .post('/', orderHeader.create)
    .post('/excel', util.getFile('orderHeaders', 'excel'), orderHeader.excel)
    .get('/create', orderHeader.getCreate)
    .get('/:id', orderHeader.get)
    .get('/product/:id', orderHeader.getFromProduct)
    .get('/:id/edit', orderHeader.edit)
    .put('/:id', orderHeader.update)
    .get('/:id/delete', orderHeader.getDelete)
    .delete('/:id', orderHeader.delete)
    .post('/export', util.getFile('orderHeaders', 'excel'), orderHeader.export)
  )
  .use('/orderDetails', authorize('ADMIN,USER'), express.Router()
    .post('/', orderDetail.create)
    .get('/create', orderDetail.getCreate)
    .get('/:id/edit', orderDetail.edit)
    .put('/:id', orderDetail.update)
    .get('/:id/delete', orderDetail.getDelete)
    .delete('/:id', orderDetail.delete)
  )
